### ISSUE TITLE
mapClusters

### ISSUE THREAD

**Issue by vincentj10** [JeremyGelb/geocmeans#1]
Hi,

First of all, thank you for developing this much needed package. 

I ran into an error using mapCluster function.
**Code**
cmeansMaps<- mapClusters(reseauALL_C_sp,Cmean$Belongings,undecided = 0.45)
**Message**
Error in fix.by(by.y, y) : 'by' must specify a uniquely valid column

where reseauALL_C_sp is a sp dataframe, the same that was used to create the membership matrix.

**Comment by JeremyGelb** [comment]
Hi and thank you for your interest in geocmeans!

The bug was caused by a typo in the function, it must be corrected now in the dev-version. To download it, please run the following command in R: 
`remotes::install_github('JeremyGelb/geocmeans@master')`

Could you confirm that the function is now working as expected? If so, I will close this issue.

**Comment by vincentj10** [comment]
It now runs smoother than a knife through butter, thanks for the quick fix!

**Comment by JeremyGelb** [comment]
it is a pleasure!
